global:
  scrape_interval: 15s # Как часто собирать метрики

scrape_configs:
  - job_name: 'binance_gateway'
    # Цель для сбора метрик: сервис 'gateway' на порту '8080'
    static_configs:
      - targets: ['gateway:8080']